In [27]:
import torch
import numpy as np

In [3]:
x = torch.empty(2, 3)    # torch.empty(size)
x = torch.rand(2, 3)     # torch.rand(size)
x = torch.zeros(2, 3)    # torch.zeros(size)
x = torch.tensor([2.5, 0.11])   # torch.tensor(list)

In [5]:
print(x.size())
print(x.dtype)

torch.Size([2])
torch.float32


In [6]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
z = torch.add(x, y) # z = x + y와 같음
print(z)

tensor([[0.3352, 0.9633],
        [0.8212, 0.1932]])
tensor([[0.5796, 0.8154],
        [0.3823, 0.4306]])
tensor([[0.9148, 1.7788],
        [1.2036, 0.6237]])


In [8]:
y.add_(x)   # In-place operation, y 변경

tensor([[1.2500, 2.7421],
        [2.0248, 0.8169]])

In [9]:
z = x - y
z = torch.sub(x,y)
print(z)
y.sub_(x)

tensor([[-0.9148, -1.7788],
        [-1.2036, -0.6237]])


In [11]:
z = x * y
z = torch.mul(x,y)
print(z)
y.mul_(x)

tensor([[0.3066, 1.7135],
        [0.9884, 0.1205]])


tensor([[0.3066, 1.7135],
        [0.9884, 0.1205]])

In [13]:
z = x / y
z = torch.div(x, y)
print(z)
y.div_(x)

tensor([[0.3664, 0.5416],
        [0.6823, 0.3097]])


tensor([[2.7289, 1.8465],
        [1.4656, 3.2290]])

In [21]:
x = torch.rand(5,3)
print(x)
print(x[:,1])   # 모든 행, 2번째 열만
print(x[0, :])  # 첫번째 행, 모든 열
print(x[0:2, :]) # 0~1 행, 모든 열

tensor([[0.8094, 0.1932, 0.2566],
        [0.9135, 0.6726, 0.6230],
        [0.5812, 0.8720, 0.4154],
        [0.9836, 0.5149, 0.6840],
        [0.5033, 0.3748, 0.4860]])
tensor([0.1932, 0.6726, 0.8720, 0.5149, 0.3748])
tensor([0.8094, 0.1932, 0.2566])
tensor([[0.8094, 0.1932, 0.2566],
        [0.9135, 0.6726, 0.6230]])


In [26]:
x = torch.rand(4,4)
print(x)
y = x.view(-1, 8)   # 전체 크기 16을, r행 8열로 reshape, 이 때 r이 -1이므로 다른 수에 의해 결정 (여기서는 2)
print(y)
y = x.view(16)
print(y)

tensor([[0.0763, 0.1896, 0.5657, 0.8755],
        [0.9608, 0.3528, 0.3295, 0.1030],
        [0.8328, 0.8356, 0.5557, 0.8558],
        [0.6118, 0.7808, 0.3534, 0.9279]])
tensor([[0.0763, 0.1896, 0.5657, 0.8755, 0.9608, 0.3528, 0.3295, 0.1030],
        [0.8328, 0.8356, 0.5557, 0.8558, 0.6118, 0.7808, 0.3534, 0.9279]])
tensor([0.0763, 0.1896, 0.5657, 0.8755, 0.9608, 0.3528, 0.3295, 0.1030, 0.8328,
        0.8356, 0.5557, 0.8558, 0.6118, 0.7808, 0.3534, 0.9279])


In [35]:
a = torch.ones(5)
print(a)
b = a.numpy()   # tensor a를 numpy array로 변경
print(b)

a.add_(1)   # 위 처럼 만든 array는 tensor의 연산에 영향 받음
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [40]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [45]:
torch.cuda.is_available()
b.device

device(type='cpu')

In [47]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
